In [48]:
print("Python is working")

Python is working

In [49]:
import pandas as pd
import numpy as np

print("Libraries imported")

Libraries imported

In [50]:
df = pd.read_csv(
    "../dataset/Hospital_Management_Records.csv"
)

In [51]:
df.shape

(10000, 25)

In [52]:
df.head()

,Patient_ID,Patient_Name,Gender,Age,Blood_Group,City,Disease,Department,Doctor,Admission_Date,...,Lab_Charge,Room_Charge,Doctor_Fee,Total_Bill,Amount_Paid,Pending_Amount,Payment_Mode,Feedback_Rating,Insurance,Insurance_Provider
0,P00001,Panini Karpe,Female,34,O-,Sambalpur,Typhoid,Nephrology,Dr. Rajesh Das,2025-02-21,...,3707,19521,6331,43606,31675,11931,Cash,4,Yes,HDFC ERGO
1,P00002,Charita Bhardwaj,Female,32,A+,Bhubaneswar,Dengue,General Medicine,Dr. Arjun Rao,2025-04-04,...,4465,7763,6734,21434,18101,3333,Debit Card,4,No,NaN
2,P00003,Kai Sachdev,Female,66,B-,Bhubaneswar,Pneumonia,Cardiology,Dr. Amit Kumar,2025-08-14,...,4243,17419,1141,28989,23522,5467,Debit Card,3,No,NaN
3,P00004,Viraj Deo,Male,61,B-,Mumbai,Hypertension,Nephrology,Dr. Sneha Patel,2025-04-01,...,4741,12317,4089,25540,15459,10081,Debit Card,5,Yes,Niva Bupa
4,P00005,Amara Ramesh,Male,87,O+,Rourkela,Dengue,General Medicine,Dr. Sneha Patel,2025-01-31,...,4634,10269,5465,29329,19899,9430,Cash,4,Yes,HDFC ERGO

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          10000 non-null  str
 1   Patient_Name        10000 non-null  str
 2   Gender              10000 non-null  str
 3   Age                 10000 non-null  int64
 4   Blood_Group         10000 non-null  str
 5   City                10000 non-null  str
 6   Disease             10000 non-null  str
 7   Department          10000 non-null  str
 8   Doctor              10000 non-null  str
 9   Admission_Date      10000 non-null  str
 10  Discharge_Date      10000 non-null  str
 11  Hospital_Stay       10000 non-null  int64
 12  Surgery             10000 non-null  str
 13  Surgery_Type        5031 non-null   str
 14  Medicine_Cost       10000 non-null  int64
 15  Lab_Charge          10000 non-null  int64
 16  Room_Charge         10000 non-null  int64
 17  Doctor_Fee          10000 non-null  int64
 18  Total_Bill          10000 non-null  int64
 19  Amount_Paid         10000 non-null  int64
 20  Pending_Amount      10000 non-null  int64
 21  Payment_Mode        10000 non-null  str
 22  Feedback_Rating     10000 non-null  int64
 23  Insurance           10000 non-null  str
 24  Insurance_Provider  4991 non-null   str
dtypes: int64(10), str(15)
memory usage: 1.9 MB

In [54]:
df.describe()

,Age,Hospital_Stay,Medicine_Cost,Lab_Charge,Room_Charge,Doctor_Fee,Total_Bill,Amount_Paid,Pending_Amount,Feedback_Rating
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,44.985700,5.473100,8027.893300,2759.545100,10994.8605,5482.335600,27264.634500,21813.149600,5451.484900,3.01080
std,26.075826,2.867002,4031.061169,1307.817006,5191.3418,2630.196555,7209.567568,6579.822305,3575.167157,1.40502
min,1.000000,1.000000,1000.000000,500.000000,2003.0000,1000.000000,7174.000000,4821.000000,2.000000,1.00000
25%,22.000000,3.000000,4559.000000,1622.000000,6518.5000,3209.750000,22133.250000,17098.750000,2529.750000,2.00000
50%,45.000000,5.000000,8010.000000,2768.000000,10961.0000,5440.000000,27197.000000,21422.000000,5014.000000,3.00000
75%,67.000000,8.000000,11504.000000,3906.250000,15459.0000,7806.250000,32339.500000,26128.250000,7981.000000,4.00000
max,90.000000,10.000000,15000.000000,5000.000000,20000.0000,9999.000000,47254.000000,46237.000000,18238.000000,5.00000

In [55]:
#check null values in column 
df.isnull().sum()

Patient_ID               0
Patient_Name             0
Gender                   0
Age                      0
Blood_Group              0
City                     0
Disease                  0
Department               0
Doctor                   0
Admission_Date           0
Discharge_Date           0
Hospital_Stay            0
Surgery                  0
Surgery_Type          4969
Medicine_Cost            0
Lab_Charge               0
Room_Charge              0
Doctor_Fee               0
Total_Bill               0
Amount_Paid              0
Pending_Amount           0
Payment_Mode             0
Feedback_Rating          0
Insurance                0
Insurance_Provider    5009
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
#create new colum df_clean
df_clean = df.copy()

In [58]:
df_clean = df_clean.drop_duplicates()

In [59]:
df_clean.duplicated().sum()

np.int64(0)

In [60]:
df_clean.columns.to_list()#to_list() show give output by list by array#df.()gives op by array by list#

['Patient_ID',
 'Patient_Name',
 'Gender',
 'Age',
 'Blood_Group',
 'City',
 'Disease',
 'Department',
 'Doctor',
 'Admission_Date',
 'Discharge_Date',
 'Hospital_Stay',
 'Surgery',
 'Surgery_Type',
 'Medicine_Cost',
 'Lab_Charge',
 'Room_Charge',
 'Doctor_Fee',
 'Total_Bill',
 'Amount_Paid',
 'Pending_Amount',
 'Payment_Mode',
 'Feedback_Rating',
 'Insurance',
 'Insurance_Provider']

In [61]:
for col in df_clean.select_dtypes(include="object"):
                    #object which is no numerical categorical
    df_clean[col] = df_clean[col].str.strip()#used for remove extra space of column name

C:\Users\HP\AppData\Local\Temp\ipykernel_27916\1523221323.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object"):

In [62]:
#df_clean["Gender"].value_counts() 
df.value_counts("Gender")

Gender
Female    5026
Male      4974
Name: count, dtype: int64

In [63]:
df_clean["Gender"] = (
    df_clean["Gender"]
    .str.lower()
    .str.capitalize()
)

In [64]:
df_clean["Admission_Date"] = pd.to_datetime(   #change data type of date used for while #df.int64
    df_clean["Admission_Date"]
)


df_clean["Discharge_Date"] = pd.to_datetime(
    df_clean["Discharge_Date"]
)

In [65]:
df.dtypes

Patient_ID              str
Patient_Name            str
Gender                  str
Age                   int64
Blood_Group             str
City                    str
Disease                 str
Department              str
Doctor                  str
Admission_Date          str
Discharge_Date          str
Hospital_Stay         int64
Surgery                 str
Surgery_Type            str
Medicine_Cost         int64
Lab_Charge            int64
Room_Charge           int64
Doctor_Fee            int64
Total_Bill            int64
Amount_Paid           int64
Pending_Amount        int64
Payment_Mode            str
Feedback_Rating       int64
Insurance               str
Insurance_Provider      str
dtype: object

In [66]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          10000 non-null  str
 1   Patient_Name        10000 non-null  str
 2   Gender              10000 non-null  str
 3   Age                 10000 non-null  int64
 4   Blood_Group         10000 non-null  str
 5   City                10000 non-null  str
 6   Disease             10000 non-null  str
 7   Department          10000 non-null  str
 8   Doctor              10000 non-null  str
 9   Admission_Date      10000 non-null  datetime64[us]
 10  Discharge_Date      10000 non-null  datetime64[us]
 11  Hospital_Stay       10000 non-null  int64
 12  Surgery             10000 non-null  str
 13  Surgery_Type        5031 non-null   str
 14  Medicine_Cost       10000 non-null  int64
 15  Lab_Charge          10000 non-null  int64
 16  Room_Charge         10000 non-null  int64
 17  Doctor_Fee          10000 non-null  int64
 18  Total_Bill          10000 non-null  int64
 19  Amount_Paid         10000 non-null  int64
 20  Pending_Amount      10000 non-null  int64
 21  Payment_Mode        10000 non-null  str
 22  Feedback_Rating     10000 non-null  int64
 23  Insurance           10000 non-null  str
 24  Insurance_Provider  4991 non-null   str
dtypes: datetime64[us](2), int64(10), str(13)
memory usage: 1.9 MB

In [67]:
df_clean["Age"].describe() #colm wise numerical value shows

count    10000.000000
mean        44.985700
std         26.075826
min          1.000000
25%         22.000000
50%         45.000000
75%         67.000000
max         90.000000
Name: Age, dtype: float64

In [68]:
#uft only used for csv file to save used for sql
df.to_csv(r"C:\Users\HP\OneDrive\Desktop\Healthcare-Analytics\dataset\cleaned_Hospital_Management_Records.csv",index=False,encoding="utf-8")

In [69]:
df.to_excel(r"C:\Users\HP\OneDrive\Desktop\Healthcare-Analytics\dataset\Hospital_Management_Records.xlsx",index=False)#does not create index ifindex =rue creat index by defult

In [70]:
df_clean.shape

(10000, 25)

In [71]:
df_clean.shape

(10000, 25)